### PR TITLE
Added Conda Environment Yaml for MacOS

### PR DESCRIPTION
**Pull request by kathlenemagnus**
I have never been able to successfully build the Olympia Conda environment on my Mac, so I'm checking in a yaml that works for me. It's derived from the Sparta Conda environment with some modifications (i.e. removing version specifications from a few libraries like boost).

### CODE REVIEW

**Comment by jeffnye-gh** [comment]
Sorry I can't try this out, I don't use macs.

**Review by jeffnye-gh — APPROVED** [review]
I'm approving so I don't block the process, but I do not have a mac, i can not try this.

**Comment by kathlenemagnus** [comment]
I will wait to merge until another MacOS user can test this out.

**Comment by klingaard** [comment]
Ugh, don't be too frustrated with this, but we actually have a MacOS environment yaml file here: https://github.com/riscv-software-src/riscv-perf-model/blob/master/.github/workflows/conda/macos_env.yml

Moving forward, can you either merge your new file into it OR have the GitHub CI use yours?  This is the line in CI that you'd update: https://github.com/riscv-software-src/riscv-perf-model/blob/791d133283861273f3649c0e05aedccd946b29a3/.github/workflows/macos-build.yml#L72

**Pull request merged**
