### PR TITLE
Ensure Queue is empty before finishing simulation

### PR DESCRIPTION
**Pull request by h0lyalg0rithm**

### CODE REVIEW

**Comment by h0lyalg0rithm** [comment]
@knute-sifive I added this assert to make sure there are no pending stores and the current model fails.Do you some ideas on this

**Comment by knute-sifive** [comment]
I ran the regression with your branch and the failure makes sense -- and doesn't.  😄 

One of the tests terminates simulation after 1M instructions have retired:
```
olympia -i 1M --workload traces/core_riscv.zstf
```
which will leave "unretired" stores in the ROB.  In other words -- that's ok!  

This test works fine:
```
olympia -i 1M --workload traces/core_riscv.zstf
```

**Comment by h0lyalg0rithm** [comment]
Got it, should I change the test cases to remove the instruction limit.

**Comment by knute-sifive** [comment]
Well, you can remove the instruction limit if you want, but the simulator _should not die_ if a user wants to only generate a pipeout or report or whatever for just the first few million instructions.  

In other words, I do not think this assert is required.

**Comment by h0lyalg0rithm** [comment]
Got it, Is there another way to get around this issue?
Its pretty useful when developing to know that all the instructions were correctly handled in the LSU

**Pull request closed without merging**
