### PR TITLE
New gen_layout commands

### PR DESCRIPTION
**Pull request by klingaard**
Removed the old perl generator; uses the new python generator in Sparta.

These changes make a few assumptions: 
1. The user is using a newer version of sparta map_v2
2. The path to the clone of map is next to the clone of olympia

### CODE REVIEW

**Comment by klingaard** [comment]
Hey @kathlenemagnus can I get a "heck ya!" approval for this?

**Review by kathlenehurt-sifive — APPROVED** [review]

**Review by kathlenehurt-sifive — APPROVED** [review]

**Review by kathlenemagnus — APPROVED** [review]

**Comment by peter-d** [comment]
Hi Knute - I run into problems with this PR, seems there are some non-ascii characters in the generated alf files that are checked in, for example in `small_core.alf`:

image

On my end (WSL2 Ubuntu), this crashes the yaml parsing when you start the pipe viewer. I haven't been able to rerun the generate script without errors, it's not clear to me what sparta version it depends on exactly to work.

**Comment by klingaard** [comment]
Ugh, I see the escape chars -- I have no idea how that happened.  I'll look at it today.

You'll need map_v2.0.7 or later to run the tools.

**Comment by klingaard** [comment]
Fix in #127

**Pull request merged**
