### PR TITLE
Update stf patch

### PR DESCRIPTION
**Pull request by light2802**
Does not work yet. DO NOT MERGE

### CODE REVIEW

**Comment by knute-sifive** [comment]
I know this is a draft, but seems to have the some of the same changes in PR #66

**Comment by light2802** [comment]
> I know this is a draft, but seems to have the some of the same changes in PR #66
Yes because this patch is on top of  PR #66 . If felt to keep both separate as they are somewhat independant

**Comment by light2802** [comment]
@knute-sifive  Can you help me with this? I cant figure out why it's not working. I tried to use gdb for debugging and basically, we never encounter an START_TRACE_OPC instruction. The same elf binary works with the old patch so its not an issue there. Thanks.

**Comment by knute-sifive** [comment]
Finally had a chance to look at this.  This commit of dromajo broke us: https://github.com/chipsalliance/dromajo/commit/c197499682181fae46652bc9989e63b572d3c274

We can either apply the patch one revision before this one or figure out how this patch broke us.

**Review by knute-sifive — APPROVED** [review]

**Comment by knute-sifive** [comment]
The latest Dromajo _hard-codes_ an instruction quantum to 10k (from just 1) which bypasses checks for trace start/stop markers.  This patch reduces the quantum back down to 1.  Eventually we will need to add trace start/stop detection in the main template of dromajo, but hopefully we'll have replaced before we need to do that.

**Pull request merged**
