### PR TITLE
Switch mavis submodule to use HTTPS

### PR DESCRIPTION
**Pull request by Shubhf**
In this pull request I have tried to update ".gitmodules" file to switch mavis (submodule) from SSH to HTTPS, this is the change which is user friendly and hassle free cloning for all users, especially for people those who do not have SSH access and prefer HTTPS for real time operations.

Updated the above mentioned file ".gitmodules" to use HTTPS for the mavis submodule:
"https://github.com/sparcians/mavis.git"
Synchronized and reinitialized  the mavis submodule to reflect the new URL.
Verified the submodule is correctly cloned and also functional with new integration.

This is a enhancement feature which improves accessibility and ease the process of setting up locally for those w/o SSH credentials.

### CODE REVIEW

**Comment by oms-vmicro** [comment]
It looks like the wrong file may have been added/staged in the commit.

I'm seeing `.gitmodules.save` in this pull-request when I believe the intended file to be updated is `.gitmodules`.

I'm happy to help so just let me know if you'd like it!

**Comment by Shubhf** [comment]
I will check again ..but will make necessary changes because I had made
changes in .gitmodules only

**Comment by Shubhf** [comment]
Respected Sir ,I have made changes pls check it

**Comment by oms-vmicro** [comment]
The change to `.gitmodules` looks good.  However, I'm still seeing `.gitmodules.save` as a new file in this commit (See https://github.com/riscv-software-src/riscv-perf-model/pull/195/files).

You'll need to do a `git rm .gitmodules.save` to remove it from the commit.

**Comment by Shubhf** [comment]
Sir I have fixed ..

**Comment by Shubhf** [comment]
Awesome, thanks!

**Review by klingaard — APPROVED** [review]
Unless CI disagrees with me, I don't see any problem with this.  Appreciate the change!

**Pull request merged**
